version: '3'
services:
  db:
    image: mongo:4.0
    container_name: sibylapp_db
    command: bash -c "mongod --bind_ip_all --port 27017 --logpath /sibylapp/log/db.log --fork && mongorestore --db sibylapp /sibylapp/dump/"
    volumes:
      - ./db/data:/sibylapp/data
      - ./db/log:/sibylapp/log
      - ./db/sibyl/sibylapp:/sibylapp/dump
